# Generated by Django 3.2.6 on 2021-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("author", models.CharField(max_length=256)),
                ("publication_date", models.CharField(max_length=10, null=True)),
                ("ISBN", models.CharField(max_length=13)),
                ("page_count", models.IntegerField(null=True)),
                ("cover_link", models.CharField(blank=True, max_length=512, null=True)),
                ("publication_language", models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
